# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

vad_webrtc_detection <- function(file, mode = 3L, milliseconds = 10L) {
    .Call('_audio_vadwebrtc_vad_webrtc_detection', PACKAGE = 'audio.vadwebrtc', file, mode, milliseconds)
}

